### ISSUE TITLE
Feature request: support for passing lists to variable argument sql functions

### ISSUE THREAD

**Issue by quickdudley** [paul-rouse/mysql-simple#30]
My motivating example is the [field()](https://dev.mysql.com/doc/refman/5.5/en/string-functions.html#function_field) function.
In the program I'm writing: I'd like to call it with a column name as the initial argument and the remaining arguments defined at runtime. Something like this:
`query conn "SELECT * FROM example_table ORDER BY field(f,?)" (Only (VaArgs [1,4,2,3]))`
I don't mind whether `VaArgs` is a new type or you just use the `In` type, but the `In` type doesn't currently work in this context.

**Comment by paul-rouse** [comment]
Closed via #31
