### ISSUE TITLE
Test requires mysql server running

### ISSUE THREAD

**Issue by kquick** [paul-rouse/mysql-simple#33]
The test makes an attempt to connect to a locally-running mysql server with a specific user and no password.  This is an external dependency that will break any tool that attempts to run the tests automatically.  Can this be removed from the cabal test specification and simply be built as an example utility instead?

**Comment by paul-rouse** [comment]
Let's close here and continue the discussion in https://github.com/paul-rouse/mysql/issues/26 sine the answer will apply to both packages.
