### ISSUE TITLE
*** Exception: foo

### ISSUE THREAD

**Issue by chrisdone** [paul-rouse/mysql-simple#39]
https://github.com/paul-rouse/mysql-simple/blob/master/Database/MySQL/Simple.hs#L164

Ran into this. Think someone forgot to finish writing the function.

**Comment by paul-rouse** [comment]
Yes, about 6 years ago by the looks of it!  Just to check, was the situation really an error - just not reported very well?

**Comment by chrisdone** [comment]
It was a proper mistake I seem to have made, presumably my query didn't match the expected regex format. But I just got that exception in my REPL and was a bit confused. :)

**Comment by paul-rouse** [comment]
Closed via https://github.com/paul-rouse/mysql-simple/commit/925aaf35dbde5efd5c574c4a3958b420e3f8a54c. Thanks for the report!

**Comment by chrisdone** [comment]
Cheers! 🍻
