### ISSUE TITLE
Support for JSON column

### ISSUE THREAD

**Issue by alex-tan** [paul-rouse/mysql-simple#42]
When trying to query a JSON column I get this error:

```
*** Exception: Database.MySQL: unknown field type 245
CallStack (from HasCallStack):
  error, called at Database/MySQL/Base/Types.hsc:104:12 in mysql-0.1.4-AEZSVdBqVyl80ZWOA9H6yD:Database.MySQL.Base.Types
```

Even being able to deserialize this into a string would be helpful so I could parse with another library like aeson.

**Comment by belevy** [comment]
https://github.com/paul-rouse/mysql/pull/45
and 
https://github.com/paul-rouse/mysql-simple/pull/52

should have this fixed now
