### ISSUE TITLE
`Param a => Param (In (Set a))` instance

### ISSUE THREAD

**Issue by seagreen** [paul-rouse/mysql-simple#44]
Would you like a PR adding such an instance? It would require adding `containers`, but hopefully that will be OK as it seems like part of the informal "Hackage standard library" at this point.

**Comment by paul-rouse** [comment]
Actually `containers` is already pulled in transitively because of `attoparsec`, so I don't see any problem with that.  So go ahead!

**Comment by paul-rouse** [comment]
Closed via #45
