### ISSUE TITLE
tuple query limited to 10

### ISSUE THREAD

**Issue by maxigit** [paul-rouse/mysql-simple#9]
It's seems that the auto conversion from query results to tuple is limited to 10-uple.
Is it a design decision or just the result of the process development being lazy (I mean : n-uple  conversion being "produced" on demand).

I'm using mysql-simple-quasi to read a table of 12 rows and it doesn't work, which is a bit frustrating.

I'm happy to do it and send a pull request if needed.

**Comment by qrilka** [comment]
@paul-rouse this issue seems to be outdated (`QueryResults` maximum tuple size is 24) but tuple instances miss instances for tuples with 20 and 21 members for some reason

**Comment by paul-rouse** [comment]
That must be a simple mistake!  Thanks for spotting it!

**Comment by paul-rouse** [comment]
Fixed via https://github.com/paul-rouse/mysql-simple/commit/ae7e3ad485ae9fb1b69bd7f72072679c5d15c7ab
